# Generated by Django 6.0.6 on 2026-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='muscle_mass',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Masa muscular en kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Fecha del registro'),
        ),
    ]
