# Generated by Django 5.0.14 on 2026-06-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_exercise_id_alter_observation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada de la rutina'),
        ),
    ]
