# Generated by Django 6.0.6 on 2026-06-23 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_routine_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routineexercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ClientExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en que se realizó el ejercicio')),
                ('repeticiones', models.PositiveIntegerField(default=1, help_text='Cantidad de repeticiones o series')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso utilizado (kg) opcional', max_digits=5, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_registrados', to=settings.AUTH_USER_MODEL)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
