# Generated by Django 5.0.14 on 2026-06-21 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_rol_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entrenador_asignado',
            field=models.ForeignKey(blank=True, help_text='Solo aplicable a clientes.', limit_choices_to={'rol': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
