# Generated by Django 6.0.6 on 2026-06-23 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entrenador_asignado',
            field=models.ForeignKey(blank=True, help_text='Permite enlazar un cliente directamente con un entrenador de la base de datos.', limit_choices_to={'rol': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto validado por Expresión Regular.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
